auto_awesome Czy chodziło Ci o: Zbudowanie TradesPage, dodanie formy,…
AdiiDev/TradingHelper pull request #4
Opened 2023-04-15 13:47 UTC by roller0201

… drawera. Dodawanie skrótów klawiszowych. 77 / 5 000 Wyniki tłumaczenia Tłumaczenie Building a TradesPage, adding a form, a drawer. Adding keyboard shortcuts.

2023-04-15 14:10 UTC, AdiiDev requested changes

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/dictionaries/DictionaryForm.js
> -import React, { useEffect } from 'react'
Trzeba przemyśleć ten komponent

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/trades/SelectForm.js
> +const SelectForm = ({ control, input, options, setValue }) => {
To mi wygląda na select jednego wyboru? Czy to ten multi?

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/trades/TradesDrawer.js
> +                      <LocalizationProvider
To trzeba wywalić do innego komponentu

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/trades/TradesForm.js
> +          {(tradesColumns !== undefined ? tradesColumns : []).map((input) => {
Coś takiego traci trochę sens dla komponentu z formą dla konkretnego modelu.

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/trades/TradesMultiSelectForm.js
> +const TradesMultiSelectForm = ({
Za mało abstrakcyjnie. To w tej chwili zadziała tylko dla tradingPairs i confirmations

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/trades/TradesTable.js
> +  }, [tableInfo.page, tableInfo.rowsPerPage, reload, filter])
Tutaj mogą być problemy

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/pages/TradesPage.js
> -import React from 'react'
Ten page ładnie wygląda

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/package.json
> +    "@date-io/date-fns": "^1.3.13",
A do czego to?

2023-04-15 14:10 UTC, AdiiDev commented on Trading/Trading/clientapp/src/App.js
> +                {showTopBar && <ApplicationTopSelect />}
Css się rozjedzie przy takim zwykłym chowaniu? Po ukryciu strona ze słownikami zajmuje całe dostępne miejsce?

2023-04-20 14:55 UTC, roller0201 commented on Trading/Trading/clientapp/src/App.js
> +  useEffect(() => {
Przerzuciłem na razie do WidgetPage, do zmian ustawień strony w przypadku schowania barów wrócimy przy dalszych etapach prac.

2023-04-20 14:56 UTC, roller0201 commented on Trading/Trading/clientapp/src/components/trades/SelectForm.js
> +const SelectForm = ({ control, input, options, setValue }) => {
Select jednego wyboru, będzie to reusable komponent.

2023-04-20 15:57 UTC, AdiiDev commented on Trading/Trading/clientapp/src/App.js
> +  useEffect(() => {
Dlaczego wracamy później do tego?

2023-04-20 15:59 UTC, AdiiDev commented on Trading/Trading/clientapp/src/components/trades/SelectForm.js
> +const SelectForm = ({ control, input, options, setValue }) => {
Jestem niemal pewien, że już taki istnieje w aplikacji. Poza tym, znowu wykorzystywany jest jakiś state co niszczy wykorzystanie react-hook-form

2023-05-22 18:50 UTC, roller0201 commented on Trading/Trading/clientapp/src/App.js
> +  useEffect(() => {
To chyba całkowicie wypadło, można wrócić do tematu.

2023-05-22 18:51 UTC, roller0201 commented on Trading/Trading/clientapp/src/components/dictionaries/DictionaryForm.js
> -import React, { useEffect } from 'react'
Komponent w większości zmieniony. Formy w słownikach działaja poprawnie, ta funkcjonalność dotycząca autouzupełniania sie nazwy w przypadku brokerAccounts dodana.

2023-05-22 18:51 UTC, roller0201 commented on Trading/Trading/clientapp/src/components/trades/SelectForm.js
> +const SelectForm = ({ control, input, options, setValue }) => {
Komponent usunięty, wykorzystany ten który był.

2023-05-22 18:55 UTC, roller0201 commented on Trading/Trading/clientapp/src/components/trades/TradesMultiSelectForm.js
> +const TradesMultiSelectForm = ({
Komponent wyrzucony i zmieniony na reusable.

2023-05-22 18:56 UTC, roller0201 commented on Trading/Trading/clientapp/src/components/trades/TradesTable.js
> +  }, [tableInfo.page, tableInfo.rowsPerPage, reload, filter])
To na co zwrociłeś uwagę jak dobrze pamiętam razem poprawialismy, natomiast komponent jeszcze jest w trakcie prac. Wymaga sporego refactoringu i wspolnego przegadania jak go dalej widzimy.

2023-05-22 18:57 UTC, roller0201 commented on Trading/Trading/clientapp/package.json
> +    "@date-io/date-fns": "^1.3.13",
Przy okazju chyba we wszystkich komponentach których się dotykałem zmieniłem formę przekazywania set z (dfsfdsd)=>(ggdgfdgfd) na zwyczajna nazwe funkcji.

2023-05-22 18:57 UTC, roller0201 commented on Trading/Trading/clientapp/src/App.js
> +                {showTopBar && <ApplicationTopSelect />}
wypadło

2023-05-26 09:26 UTC, merged